# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{socky-client}
  s.version = "0.4.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Bernard Potocki"]
  s.date = %q{2010-10-30}
  s.description = %q{Socky is a WebSocket server and client for Ruby}
  s.email = %q{bernard.potocki@imanel.org}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "CHANGELOG.md",
     "README.md",
     "Rakefile",
     "VERSION",
     "lib/socky-client.rb",
     "lib/socky-client/websocket.rb",
     "socky_hosts.yml",
     "spec/socky-client_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://imanel.org/projects/socky}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Socky is a WebSocket server and client for Ruby}
  s.test_files = [
    "spec/socky-client_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.0"])
    else
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.0"])
    end
  else
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.0"])
  end
end

